language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  - CFLAGS="-Wall -Wextra -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute"

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - sh autogen.sh

before_script:
  - ./configure

script:
  - make
  - export VERBOSE=1
  - make check
