language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - sh autogen.sh

before_script:
  - ./configure

script:
  - make
  - export VERBOSE=1
  - make check
